### ISSUE TITLE
Prevent users from depositing decimal REN amounts

### ISSUE THREAD

**Issue by acuarica** [renpool/renpool-app#5]
> Migrated from card https://github.com/Ethernautas/renpool/projects/1#card-67411417

Possibly set values to be 5k, 10k, or some pre-define amounts.

**Comment by fede-rodes** [comment]
@acuarica that’s correct, we can unify these 2 issues. Basically the idea was to prevent users from depositing decimal amounts + probably preset said amounts to be 5000, 10000 or so

**Comment by acuarica** [comment]
Closing this, as it's duplicate of #3.
